In [18]:
import pandas as pd

In [19]:
data=pd.read_csv("Weather.csv")

In [20]:
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# SCATTER PLOT

In [21]:
import matplotlib.pyplot as pt
%matplotlib

Using matplotlib backend: TkAgg

In [31]:
pt.scatter(data["MinTemp"],data["MaxTemp"])

In [32]:
dataset=pd.read_csv("2019_nC0v_20200121_20200126_cleaned.csv")

In [33]:
dataset

,Unnamed: 0,Province/State,Country,Date last updated,Confirmed,Suspected,Recovered,Deaths
0,0,Shanghai,Mainland China,1/21/2020,9,10,0,0
1,1,Yunnan,Mainland China,1/21/2020,1,0,0,0
2,2,Beijing,Mainland China,1/21/2020,10,0,0,0
3,3,Taiwan,Taiwan,1/21/2020,1,0,0,0
4,4,Jilin,Mainland China,1/21/2020,0,1,0,0
...,...,...,...,...,...,...,...,...
363,363,0,France,1/26/2020 11:00,3,0,0,0
364,364,0,Australia,1/26/2020 11:00,4,0,0,0
365,365,0,Nepal,1/26/2020 11:00,1,0,0,0
366,366,0,Malaysia,1/26/2020 11:00,4,0,0,0
367,367,Ontario,Canada,1/26/2020 11:00,1,0,0,0

In [34]:
pt.scatter(dataset["Confirmed"],dataset["Country"])

In [42]:
pt.pie(dataset["Confirmed"][:5],labels=dataset["Province/State"][:5])

([<matplotlib.patches.Wedge at 0x19a05afb890>,
  <matplotlib.patches.Wedge at 0x19a05afb250>,
  <matplotlib.patches.Wedge at 0x19a05ecd550>,
  <matplotlib.patches.Wedge at 0x19a05ece610>,
  <matplotlib.patches.Wedge at 0x19a05ecf5d0>],
 [Text(0.2447730130080499, 1.0724207066739067, 'Shanghai'),
  Text(-1.0511300959415604, 0.3242306608047521, 'Yunnan'),
  Text(-0.24477298790623175, -1.0724207124032321, 'Beijing'),
  Text(1.087713916065691, -0.16394644490515556, 'Taiwan'),
  Text(1.0999999999999988, 5.149471657675648e-08, 'Jilin')])

In [49]:
pt.bar(dataset["Province/State"],dataset["Confirmed"])